export let peliculas=[
    {
        nombre:"A Most Violent Year",
        genero:"Crimen",
        duracion:"2H5Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/amostviolentyear.jpg?alt=media&token=ff75caf7-b724-499d-b59c-901398c0366f",
        sinopsis:"En la ciudad de Nueva York de 1981, un ambicioso inmigrante lucha para proteger a su empresa y su familia durante el año más peligroso de la historia de la ciudad.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"J.C. Chandor",
        actores:"Oscar Isaac, Jessica Chastain, David Oyelowo",
    },
    {
        nombre:"Climax",
        genero:"Drama",
        duracion:"1H37Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/climax.jpg?alt=media&token=8cefd327-cea8-4e7e-be06-bfbc2e58cfd0",
        sinopsis:"Uno grupo de bailarines franceses se reúne en una escuela abandonada y remota para ensayar en una noche invernal. Una fiesta que iba a durar toda la noche se transforma en una pesadilla plagada de alucinaciones cuando descubren que su sangría está envenenada con LSD.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Gaspar Noé",
        actores:"Sofia Boutella, Romain Guillermic, Souheila Yacoub",
    },
    {
        nombre:"Enemy",
        genero:"Misterio",
        duracion:"1H31Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/enemy.jpg?alt=media&token=ec5b744a-6a4c-4b2a-b4a5-2948f58e6449",
        sinopsis:"Un hombre busca a su doble tras verle en una película.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Denis Villeneuve",
        actores:"Jake Gyllenhaal, Mélanie Laurent, Sarah Gadon",
    },
    {
        nombre:"Ex Machina",
        genero:"Ciencia Ficcion",
        duracion:"1H48Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/exmachina.jpg?alt=media&token=d1093b55-2a6f-4466-87aa-5f959e118097",
        sinopsis:"Un joven programador es seleccionado para participar en un innovador experimento de inteligencia sintética evaluando las cualidades humanas de una inteligencia artificial humanoide muy avanzada.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Alex Garland",
        actores:"Alicia Vikander, Domhnall Gleeson, Oscar Isaac",
    },
    {
        nombre:"A Ghost Story",
        genero:"Fantasia",
        duracion:"1H32Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/ghosthistory.jpg?alt=media&token=1d103458-55f9-4f0b-a5f7-53b32bfb18e9",
        sinopsis:"En esta singular exploración del legado, el amor, la pérdida y la enormidad de la existencia, un fantasma de piel blanca recientemente fallecido regresa a su hogar suburbano para tratar de reconectarse con su desposeída esposa.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"David Lowery",
        actores:"Casey Affleck, Rooney MaraMc, Colm Cephas Jr.",
    },
    {
        nombre:"Good Time",
        genero:"Crimen",
        duracion:"1H42Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/goodtime.jpg?alt=media&token=cddf8c3d-9687-4de6-b0b3-dc8975eb615c",
        sinopsis:"Después de que un robo de banco chapucero lleva a su hermano menor a la cárcel, Connie Nikas se embarca en una odisea retorcida a través del inframundo de la ciudad en un intento cada vez más desesperado y peligroso de sacar a su hermano Nick de la cárcel.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Benny Safdie, Josh Safdie",
        actores:"Robert Pattinson, Benny Safdie, Jennifer Jason Leigh",
    },
    {
        nombre:"Hereditary",
        genero:"Terror",
        duracion:"2H7Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/hereditary.jpg?alt=media&token=c3d7294c-1073-4170-85f4-84dd213ec666",
        sinopsis:"Tras la muerte de la matriarca, el duelo de una familia es perturbado por hechos trágicos e inquietantes, y empiezan descubrir oscuros secretos.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Ari Aster",
        actores:"Toni Collette, Milly Shapiro, Gabriel Byrne",
    },
    {
        nombre:"Lady Bird",
        genero:"Drama",
        duracion:"1H34Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/ladybird.jpg?alt=media&token=1549c3a7-7ba5-4e94-a1af-3c3223616c33",
        sinopsis:"En 2002, una joven de diecisiete años con inclinaciones artísticas alcanza la mayoría de edad en Sacramento, California.",
        clasificacion:"+13",
        idioma:"Ingles",
        director:"Greta Gerwig",
        actores:"Saoirse Ronan, Laurie Metcalf, Tracy Letts",
    },
    {
        nombre:"El faro",
        genero:"Drama",
        duracion:"1H49Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/lighthouse.png?alt=media&token=f97abd1c-3b06-4a92-a329-c14caeb3c17e",
        sinopsis:"La historia de un guardián del faro llamado Old en la Maine de principios del siglo XX.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Robert Eggers",
        actores:"Robert Pattinson, Willem Dafoe, Valeriia Karaman",
    },
    {
        nombre:"Midsommar",
        genero:"Misterio",
        duracion:"2H28Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/midsommar.jpg?alt=media&token=3ac362eb-5239-4dd6-aa89-dcb96bbe5142",
        sinopsis:"Un joven convence a su novia de que le acompañe a un festival de verano en Suecia que resulta no ser lo que parece.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Ari Aster",
        actores:"Florence Pugh, Jack Reynor, ilhelm Blomgren",
    }
]
export let estrenos=[
    {
        nombre:"Saint Maud",
        genero:"Terror",
        duracion:"1H24Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/saintmaud.jpg?alt=media&token=dc86e434-1413-4868-9559-1dc4277b7445",
        sinopsis:"Sigue a una enfermera piadosa que se obsesiona peligrosamente con salvar el alma de una paciente terminal, a cualquier precio.",
        clasificacion:"+18",
        idioma:"Ingles",
        director:"Rose Glass",
        actores:"Morfydd Clark, Caoilfhionn Dunne, Jennifer Ehle",
    },
    {
        nombre:"The Florida Project",
        genero:"Drama",
        duracion:"1H51Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/thefloridaproject.jpg?alt=media&token=b78f4a8a-07ed-4d5b-b7b3-0ee8f1d0e2ca",
        sinopsis:"Moonee, una niña precoz de seis años, pasa el verano a la sombra de Walt Disney World jugando y haciendo travesuras con sus amigos y estrechando vínculos afectivos con su rebelde pero cariñosa madre.",
        clasificacion:"+16",
        idioma:"Ingles",
        director:"Sean Baker",
        actores:"Brooklynn Prince, Bria Vinaite, Willem Dafoe",
    },
    {
        nombre:"The Witch",
        genero:"Terror",
        duracion:"1H32Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/thegreenknight.jpg?alt=media&token=881b4eae-d4d5-4710-950f-1f52b8b93a1f",
        sinopsis:"Una familia de la Nueva Inglaterra de 1630 se ve desgarrada por las fuerzas de la brujería, la magia negra y la posesión.",
        clasificacion:"+16",
        idioma:"Ingles",
        director:"Robert Eggers",
        actores:"Anya Taylor-Joy, Ralph Ineson, Kate Dickie",
    },
    {
        nombre:"El Caballero Verde",
        genero:"Aventura",
        duracion:"2H10Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/thekillingofasacreeddeer.jpg?alt=media&token=89a4cf2f-8aff-4849-9af3-a260a76a1893",
        sinopsis:"La fantástica historia medieval de Sir Gawain y el Caballero Verde reimaginada.",
        clasificacion:"+16",
        idioma:"Ingles",
        director:"David Lowery",
        actores:"Dev Patel, Alicia Vikander, Joel Edgerton",
    },
    {
        nombre:"El sacrificio de un ciervo sagrado",
        genero:"Misterio",
        duracion:"2H1Min",
        poster:"https://firebasestorage.googleapis.com/v0/b/cinebl.appspot.com/o/thewitch.jpg?alt=media&token=988f3ce6-5c07-445e-bd83-7d98f1547d32",
        sinopsis:"Steven, un carismático cirujano, se ve obligado a hacer un sacrificio impensable cuando su vida empieza a desmoronarse por culpa del siniestro comportamiento del adolescente que ha tomado bajo su protección.",
        clasificacion:"+16",
        idioma:"Ingles",
        director:"Yorgos Lanthimos",
        actores:"Barry G. Bernson, Herb Caillouet, Bill Camp",
    }
]